### ISSUE TITLE
the same question 0.5.0 xgbValue is not defined

### ISSUE THREAD

**Issue by xiaoluoyfy** [openscoring/openscoring-python#11] opened 2019-04-16 07:17 UTC
when use xgboost pmml to predict occur xgbValue is not defined

**Comment by vruusmann** [comment] 2019-04-16 18:33
Closing as duplicate of https://github.com/openscoring/openscoring/issues/47

The exception happens in the server side, not the client side.

**Closed as completed by vruusmann** 2019-04-16 18:33 UTC
